### ISSUE TITLE
EPIC: Empty/Missing/None/NaN Read/Write/Append/Update Issues

### ISSUE THREAD

**Issue by DrNickClarke** [man-group/ArcticDB#1164]
**Primary**
- [ ] https://github.com/man-group/ArcticDB/issues/1107
- [ ] https://github.com/man-group/ArcticDB/issues/224
- [ ] https://github.com/man-group/ArcticDB/issues/90
- [ ] https://github.com/man-group/ArcticDB/issues/1012

**Secondary**
- [ ] https://github.com/man-group/ArcticDB/issues/1146
