### ISSUE TITLE
ArcticDB on Conda

### ISSUE THREAD

**Issue by mehertz** [man-group/ArcticDB#168]
Requirements for having a package on conda-forge:

- [x] package [lmdbxx](https://github.com/drycpp/lmdbxx)
- [x] package [recycle](https://github.com/steinwurf/recycle)
- [x] package [rapidcheck](https://github.com/emil-e/rapidcheck) (not required for the conda package, but for testing this repo in the CI if we want to get rid of the git submodules)
- [x] refactor the code so that it does not assume dependencies are installed under `thirdparty`
- [x] provide an `environment.yml` file to get the dependencies with mamba

**Comment by JohanMabille** [comment]
This requires some refactoring regarding the management of dependencies and the build:

- ArcticDB should not vendor its dependencies
- ArcticDB should not make any assumption on the location of it dependencies, this should be configured via cmake
- github submodules are considered as a bad practice regarding dependencies management and should be avoided.

If you agree, I can start to work on the refactoring.

In parallel, I can start packaging the missing dependencies on conda-forge:
- lmdbxx
- recycle
- rapidcheck

**Comment by SylvainCorlay** [comment]
Setting up the packaging with mamba/conda and enable CI on all platforms supported by conda-forge (OS X, OS X ARM, Windows, Windows, Linux ARM, Linux PPC) sounds like an excellent first objective.

This will also prepare the project to be properly packaged for e.g. Linux distributions, as most of them disallow the vendoring of dependencies.

**Comment by JohanMabille** [comment]
> I don't know too much about Conda - could you please explain what you mean by this? Do you mean that ArcticDB shouldn't statically/dynamically (using auditwheel) dependencies, or that ArcticDB shouldn't compile dependencies into the binary using submodules?

I meant ArcticDB should not comple dependencies into the binary, whatever the method it uses to get the dependencies.

> Does Conda require build dependencies to be on conda-forge?

Yes. Conda is a package manager (among other things), so when you build a package for Conda, the dependencies have to be Conda packages too.

 > We are using vcpkg for dependency resolution - is this not best practise for Conda?

Since Conda is a package manager, it is not advised to use another package manager for dependency resolution when building a conda package. The only use-case for this is when you biuld a full statically linked binary, because full static packages are not always available on conda-forge. But this is a workaround to a conda-forge issue we are trying to fix.

> Sounds great! We're currently building for Linux X86 and Windows X86 - we've not tried to build against OS X or for ARM, though I can't imagine there are any major blockers.

The conda-forge recipes let you choose the platforms you build your package for. We can start with Linux and Windows, and add OSX and ARM later. These are usually good at pointing to code issues, especially non standard compliance.

**Comment by willdealtry** [comment]
This all sounds like a very good idea, no objections from my end.
