### ISSUE TITLE
AWS replication replicates data out of order causing errors when `read`ing from the replicated-to bucket

### ISSUE THREAD

**Issue by mehertz** [man-group/ArcticDB#588]
### Describe the bug

AWS replicates data out-of-order. When referring to the [ArcticDB storage format](https://docs.arcticdb.io/technical/on_disk_storage/), this results on the upper levels of the tree being replicated prior to the lower levels of the tree.

As a result, reads fail. Observed errors:

```
line 1586, in _read_dataframe
    return ReadResult(*self.version_store.read_dataframe_version(symbol, version_query, read_query, read_options))
arcticdb_ext.storage.NoDataFoundException: <symbol>
```

```
line 1586, in _read_dataframe
    return ReadResult(*self.version_store.read_dataframe_version(symbol, version_query, read_query, read_options))
arcticdb_ext.exceptions.StorageException: Composite: d:BBG00GD1JMY1/None:544:0x1d6d9bb0060ab3d3@1688984724249616469[1688563800000000000,1688759940000000001], 
```

Note, there may be other errors with the same cause not described here.

### Steps/Code to Reproduce

Use [AWS bucket replication](https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication.html) to replicate between buckets.

`batch_read` symbols as they are being replicated (note any read operation would suffice to expose the issue - `batch_read` was used for the above stack traces).

### Expected Results

The following resolutions would be acceptable:

* Optionally returning the most-recent _fully available_ version
* Making it easier to read versions that are likely to have been replicated

### OS, Python Version and ArcticDB Version

All versions are affected

### Backend storage used

AWS S3

**Comment by mehertz** [comment]
We will address this in the short-term by making three changes:

- [] #531 will enable users to retry failed reads in a manner of their choosing. If one symbol has not replicated whikst other reads have succeeded, they'll receive the required information to retry that read.
- [ ] #589 enables negatives integers. This would enable selecting the second-newest version by passing in `-2` as an `as_of` parameter. Note this isn't a full-proof solution as it is possible the second-newest version also hasn't replicated.
- [ ] #590 unblocks #589 to work even if the version-ref key replicates prior to the version key (theoretical issue).

**Comment by poodlewars** [comment]
There is also work on a standalone custom replication tool under https://github.com/man-group/arcticdb-enterprise/issues/49
