### ISSUE TITLE
EPIC: 4.0.X Man Group internal migration

### ISSUE THREAD

**Issue by alexowens90** [man-group/ArcticDB#951]
- [x] Create 4.0.x branch off the 4.0.0 release tag @poodlewars - Done, branch is called `4.0.x` and is protected
- [ ] Port batch read with snapshots fix to 4.0.x branch @willdealtry 
- [ ] Port static semi-map fix to 4.0.x branch @willdealtry 
- [x] Port lz4 decoding error fix to 4.0.x branch @willdealtry 
- [x] #986  @phoebusm 
- [x] #940  @jjerphan 
- [x] #987 @jjerphan 
- [ ] #1122 @jjerphan 
- [ ] https://github.com/man-group/arcticdb-man/issues/45 @vasil-pashov 
- [x] Port flaky test fix in commit b95fd30b3 to 4.0.x branch @alexowens90 
- [x] Port S3 allowed chars fix in commit a2ca480d5 to 4.0.x branch @poodlewars PR #952 
- [x] Port string encoding error message improvement in a3e96d170 to 4.0.x branch @alexowens90 
- [x] Port linux c++ test cleanup fix in c14e4c16a to 4.0.x branch @alexowens90 
- [ ] Fix read pipeline for tick streaming libraries @joe-iddon 
- [x] Release 4.0.1
- [x] Release 4.0.2
- [x] Release 4.0.3
- [ ] Release 4.0.4
- [ ] Possible performance regression https://github.com/man-group/arcticdb-man/issues/62

**Comment by poodlewars** [comment]
I've moved the details on this one to private issue https://github.com/man-group/arcticdb-man/issues/77
